//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Design.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrailerDriver
    {
        public int Id { get; set; }
        public Nullable<int> IdDriver { get; set; }
        public Nullable<int> IdTrailer { get; set; }
        public Nullable<int> IdOrder { get; set; }
        public Nullable<int> IdRoleInTrailer { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Order Order { get; set; }
        public virtual RoleInTrailer RoleInTrailer { get; set; }
        public virtual Trailer Trailer { get; set; }
    }
}
